package agh.edu.pl.gui.enums;

/**
 * Created by Dominik on 2015-12-19.
 */
public enum Commands {
    CHANGE_AUTOMATON("CHANGE_AUTOMATON"),
    CHANGE_CELL_COUNT("CHANGE_CELL_COUNT"),
    START_AUTOMATON("START_AUTOMATON"),
    PAUSE_AUTOMATON("PAUSE_AUTOMATON"),
    RAND_CELLS("RAND_CELLS"),
    CHANGE_SIMULATION_DELAY("CHANGE_SIMULATION_DELAY"),
    CLEAR_AUTOMATON("CLEAR_AUTOMATON"),
    INSERT_STRUCT("INSERT_STRUCT"),
    CANCEL_INSERTING_STRUCT("CANCEL_INSERTING_STRUCT"),
    CHANGE_NEIGHBORHOOD_TYPE("CHANGE_NEIGHBORHOOD_TYPE"),
    CHANGE_NEIGHBORHOOD_RADIUS("CHANGE_NEIGHBORHOOD_RADIUS"),
    SET_WRAP("SET_WRAP"),
    CHANGE_ONE_DIM_RULES("CHANGE_ONE_DIM_RULES"),
    CHANGE_TWO_DIM_RULES("CHANGE_TWO_DIM_RULES");

    private final String text;

    Commands(final String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return text;
    }
}
